#include<bits/stdc++.h>
using namespace std;
typedef long long int ll;

int poww(int n,int x,int p){
    int res=1;
    for(int i=1;i<=x;++i){
        res=(res*n)%p;
    }
    return res;
}
int main() 
{ 
    srand((unsigned)time(0)); 
    ll p,x,y,r1,r2,k,g;
    cout<<"Enter value of g: ";
    cin>>g;
    cout<<"Enter value of p: ";
    cin>>p;
    x = rand()%p;
    cout<<"\nRandom X generated is: "<<x;
    r1=((int)poww(g,x,p))%p;
    cout<<"\nR1 is: "<<r1;
    
    y = rand()%p;
    cout<<"\nRandom Y generated is: "<<y;
    r2=((int)poww(g,y,p))%p;
    cout<<"\nR2 is: "<<r2;
    k=((int)poww(r2,x,p))%p;
    cout<<"\nKey generated by Alice is: "<<k;
    k=((int)poww(r1,y,p))%p;
    cout<<"\nKey generated by Bob is: "<<k;
}

/*OUTPUT: 
Enter value of g: 7                                                                                                                                        
Enter value of p: 23                                                                                                                                       
                                                                                                                                                           
Random X generated is: 18                                                                                                                                  
R1 is: 18                                                                                                                                                  
Random Y generated is: 19                                                                                                                                  
R2 is: 11                                                                                                                                                  
Key generated by Alice is: 16                                                                                                                              
Key generated by Bob is: 16*/
